### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by OrionRandD** [pelhage/rhymer#13]
Hi,
Could you improve your Readme file documentation for rhyme?
How to call it, flags, etc.
I installed an app with
npm install rhymer
I do not know if it is the same as this, since no mention of npm is found here.
Also,  call the npm version with "rhyme" command, instead of "rhymer".
Are they the same?

**Comment by pelhage** [comment]
Hi @OrionRandD, I completely missed your issue

Were you able to get the CLI working? Are you using it? I'm currently working on making improvements, so if you have any feature requests let me know!

I'll be updating the README with more documentation in the coming days and will report back to you!

**Comment by OrionRandD** [comment]
Nope. The cli I have here is called rhyme 

 whatis rhyme
rhyme (1)            - display list of rhymes
And is written by another person

man rhyme shows some infos, including:
AUTHOR
       Written by Brian Langenberger.
REPORTING BUGS
       Report bugs to <bri@cbs.umn.edu>.

But, yes. "rhyme" fully works here.

Aren't you writing a redundant app?
Perhaps you can contact the author or rhyme...

**Comment by pelhage** [comment]
@OrionRandD rhyme isn't a command line tool and also hasn't been updated in 9 years

This project is made for fun and my own use so whether it's redundant or not doesn't really matter haha

**Comment by OrionRandD** [comment]
@pelhage Sorry for that. I did not mean to upset you.
All the best.
